name: vale
version: 2.15.4
summary: A syntax-aware linter for prose built with speed and extensibility in mind.
description: |
  Vale is a command-line tool that brings code-like linting to prose.
  It's fast, cross-platform, and highly customizable.

confinement: strict
grade: stable

base: core20
parts:
  deps:
    plugin: python
    python-packages:
      - docutils

  vale:
    plugin: dump
    stage-packages:
      - asciidoctor
    source: https://github.com/errata-ai/vale/releases/download/v$SNAPCRAFT_PROJECT_VERSION/vale_$SNAPCRAFT_PROJECT_VERSION_Linux_64-bit.tar.gz

apps:
  vale:
    command: vale
    plugs:
      - home
