name: Repository Dispatch
on:
  repository_dispatch:
    types: [bump-pkg]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.version }}
      - run: echo ${{ github.event.client_payload.version }}
